# Generated by Django 4.2.4 on 2023-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=1000.0, max_length=10),
        ),
    ]
