# Generated by Django 4.2.4 on 2023-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
